# Project information
site_name: TrainTrack
site_url: https://murnanedaniel.github.io/train-track/
site_author: Daniel Murnane on behalf of Exa.TrkX Collaboration

# Repo
repo_url: https://github.com/murnanedaniel/train-track
repo_name: TrainTrack

nav:
  - Home: index.md
  - Pipelines:
    - Overview: pipelines/overview.md
    - Quickstart: pipelines/quickstart.md
    - Choosing a template: pipelines/choosingguide.md
    - "Use Case: TrackML GNN Edge Classification": pipelines/trackmlGNN.md
    - "Use Case: TrackML Metric Learning": pipelines/trackmlembedding.md
  - Models:
    - Overview: models/overview.md
    - Hyperparameter Guide: models/hpguide.md
    - Typical Mileage: models/performance.md
    - Zoology and Taxonomy: models/taxonomy.md
  - Performance:
    - Overview: performance/overview.md
    - Definitions: performance/definitions.md
    - Use Cases: performance/usage.md
  - Tools:
    - Overview: tools/overview.md
    - Data Manipulation: tools/data.md
    - Training & Inference: tools/ml.md
    - PyLightning & MLFlow: tools/frameworks.md


theme:
  name: material
  palette:
    primary: white
    accent: indigo
  # logo: media/favicon.png
  # favicon: media/favicon.ico
  features:
    - navigation.tabs
    - navigation.instant

plugins:
  - search
  - mkdocstrings
#       default_handler: python
#       watch:
#         - src/Pipelines/TrackML_Example/LightningModules
